---
- name: Install and Configure Jenkins on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Add Jenkins APT Key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins APT Repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins service is started and enabled
      service:
        name: jenkins
        state: started
        enabled: yes

    # Adding the jenkins user to the ubuntu group
    - name: Add Jenkins user to the ubuntu group
      user:
        name: jenkins
        groups: ubuntu
        append: yes

    # Setting permissions
    - name: Set permission for /home/ubuntu directory
      file:
        path: /home/ubuntu
        mode: '0750'

    - name: Set permission for /home/ubuntu/.ssh directory
      file:
        path: /home/ubuntu/.ssh
        mode: '0750'

    - name: Set permission for /home/ubuntu/.ssh/mtckey.pub
      file:
        path: /home/ubuntu/.ssh/mtckey.pub
        mode: '0644'
        
        - name: Set permission for /home/ubuntu/.aws directory
      file:
        path: /home/ubuntu/.aws
        mode: '0750'

    - name: Set permission for /home/ubuntu/.aws/credentials
      file:
        path: /home/ubuntu/.aws/credentials
        mode: '0640'

