---
- name: Install and Configure Jenkins on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Set timezone to Pacific Time
      ansible.builtin.timezone:
        name: America/Los_Angeles
        
    - name: Add Jenkins APT Key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins APT Repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins service is started and enabled
      service:
        name: jenkins
        state: started
        enabled: yes

    # Adding the jenkins user to the ubuntu group
    - name: Add Jenkins user to the ubuntu group
      user:
        name: jenkins
        groups: ubuntu
        append: yes

    # Setting permissions for multiple directories and files
    - name: Set permissions
      file:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: '/home/ubuntu', mode: '0750' }
        - { path: '/home/ubuntu/.ssh', mode: '0750' }
        - { path: '/home/ubuntu/.ssh/mtckey.pub', mode: '0644' }
        - { path: '/home/ubuntu/.aws', mode: '0750' }
        - { path: '/home/ubuntu/.aws/credentials', mode: '0640' }

    - name: Restart Jenkins service
      service:
        name: jenkins
        state: restarted
